### ISSUE TITLE
Traefik Plugins: unable to create plugins due to read-only file system

### ISSUE THREAD

**Issue by spatterIight** [devture/com.devture.ansible.role.traefik#14]
### Configuration

```
devture_traefik_configuration_extension_yaml: |
  experimental:
    plugins:
      geoblock:
        moduleName: "github.com/PascalMinder/geoblock"
        version: "v0.2.8"
```

### Error:

`Sep 04 01:55:12 lainon traefik[13393]: time="2024-09-04T01:55:12Z" level=error msg="Plugins are disabled because an error has occurred." error="unable to create plugins client: unable to create directory /plugins-storage/sources: mkdir plugins-storage: read-only file system"`

### Work-around

I was able to temporarily work-around this issue by using `localPlugins` and `mounting` the plugin

```
devture_traefik_configuration_extension_yaml: |
  experimental:
    localPlugins:
      geoblock:
        moduleName: github.com/PascalMinder/geoblock
```

```
devture_traefik_container_extra_arguments_custom:
  - "--volume /srv/traefik/geoblock:/plugins-local/src/github.com/PascalMinder/geoblock"
```

---

Going to look at making a pull request to handle this without needing the work-around
